Update on 1-5

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,14 @@
 #!/bin/bash
-python3 -c "$PYCODE"
+
+# Get the Python code from the environment variable
+python_code="$PYCODE"
+
+# Check if PYCODE is set
+if [ -z "$python_code" ]; then
+    echo "Error: PYCODE environment variable is not set."
+    exit 1
+fi
+
+# Run the Python code
+python -c "$python_code"
+
